from typing import Protocol


class FileStorage(Protocol):
    def save_avatar(self, user_id: int, data: bytes, content_type: str) -> str: ...
    def save_post_image(self, data: bytes, content_type: str) -> str: ...
    def delete_if_exists(self, relative_path: str | None) -> None: ...
