from typing import Protocol

from blog_app.domain.entities.post import Post


class PostRepository(Protocol):
    def add(self, post: Post) -> Post: ...
    def get_by_id(self, post_id: int) -> Post | None: ...
    def list_all(self, skip: int = 0, limit: int = 100) -> list[Post]: ...
    def list_by_author(self, author_id: int, skip: int = 0, limit: int = 100) -> list[Post]: ...
    def update(self, post: Post) -> Post: ...
    def delete(self, post_id: int) -> None: ...
