from typing import Any, Protocol


class TokenService(Protocol):
    def create_access_token(
        self, subject: str, extra_claims: dict[str, Any] | None = None
    ) -> str: ...
    def create_refresh_token(self, subject: str) -> str: ...
    def decode_token(self, token: str) -> dict[str, Any]: ...
    def subject_from_refresh_token(self, token: str) -> int | None: ...
